# .github/workflows/deploy.yml

name: Deploy

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        echo "Deploying to production..."

  build:
    runs-on: ubuntu-latest
    needs: install  # Ensure this job runs after the install job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build project
      run: |
        echo "Deploying to production..."

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job
    environment:
      name: production  # Specify environment for deployment approval
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to production
      run: |
        echo "Deploying to production"
