name: Manual Approval

on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Manual approval input'
        required: true
        type: boolean

jobs:
  install:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy == 'true' }}
    steps:    
    - name: Manual Workflow Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: anassaleem021,anassaleem
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        echo "Deploying to production..."

  build:
    runs-on: ubuntu-latest
    needs: install  # Ensure this job runs after the install job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build project
      run: |
        echo "Deploying to production..."

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job
    environment:
      name: production  # Specify environment for deployment approval
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to production
      run: |
        echo "Deploying to production"
