on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Manually approve deployment'
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy code
        if: ${{ github.event.inputs.deploy == 'true' }}
        run: |
          echo "Deploying application"
          # Add your deployment commands here
