on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Manually approve deployment'
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy == 'true' }}
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: anassaleem021

      - name: Deploy code      
        run: |
          echo "Deploying application"
          # Add your deployment commands here
