name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  manual-approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: user1,user2
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"

  deploy:
    runs-on: ubuntu-latest
    needs: manual-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: echo "Deploying to production..."
        # Add your deployment commands here
